add ability to post a new comment under an article
Holquaria/nc-news pull request #6
Opened 2023-01-10 13:54 UTC by Holquaria

2023-01-10 14:24 UTC, popatre requested changes
Looks good so far, just a few things to add;

- Stop someone posting an empty comment
- Could you lock the button after posting so they can't accidentally click it twice, especially if slow?
- Can you add a little login button - that logs you in as tickle. Then stop them posting if not logged in?
- Make the form a controlled component

2023-01-10 14:24 UTC, popatre commented on src/components/NewComment.jsx
> +        <input className="new-comment-body" type="text" name="body"></input>
This needs to be textarea - to allow multi line comments. 
Also, its not currently a controlled component - react isnt in control of this at the moment and wouldnt know whats in the form until its submitted. You can run into rendering issues.

2023-01-10 16:40 UTC, Poonam-raj approved these changes
Few things I'd like you to extract to debloat the code, Jamie, but otherwise nice work! I had one comment about the form so feel free to address my comments and then merge this work 🚀

2023-01-10 16:40 UTC, Poonam-raj commented on src/components/VoteBlock.jsx
>          .catch(() => {
Line 13 can be removed

2023-01-10 16:40 UTC, Poonam-raj commented on src/components/Comments.jsx
>              </li>
Lines 29 - 35 definitely could be extracted into another component to stop this component from bloating up

2023-01-10 16:40 UTC, Poonam-raj commented on src/components/NewComment.jsx
> +  console.log(newComment);
Remove console logs before making PRs and definitely before merging!

2023-01-10 16:40 UTC, Poonam-raj commented on src/components/NewComment.jsx
> +        </div>
This error component could be extracted out to reduce bloating of component

2023-01-10 16:40 UTC, Poonam-raj commented on src/components/NewComment.jsx
> +          }}
value attribute should ideally be here should be newComment if this is truly a controlled component

2023-01-11 09:21 UTC, Poonam-raj approved these changes
Nice work please merge!

2023-01-11 09:23 UTC, merged